### ISSUE TITLE
리브레오피스5.2에서

### ISSUE THREAD

**Issue by yueunseon** [cogniti/dalkom#1]
안렁하세요?
리브레오피스 사이트에서 설치파일로 설치하니
실행할때 libreoffice5.2 --writer 식으로 5.2 가 들어가는 데요.
설치한 달콤을 어떡게 수정해얄지 혹시 알려주실수있나요? 감삽니다.

**Comment by cogniti** [comment]
운영체제가 어떻게 되는데요?

**Comment by cogniti** [comment]
우분투 사용하시는 거라면 우분투 공식 저장소에서 제공하는 libreoffice 를 사용하시기 바랍니다.
